chore: remove changelog
go-vela/ui pull request #526
Opened 2022-03-07 20:23 UTC by kaymckay

2022-03-07 23:05 UTC, ecrupper submitted a review, later dismissed

2022-03-08 15:13 UTC, wass3r requested changes
so, there is some inconsistency here between the other repos. in this case `release.yml` actually doesn't generate the release notes. in this case it's `publish.yml`.

2022-03-08 15:38 UTC, kaymckay commented
@wass3r can we rename it to publish.yml then?

2022-03-08 16:29 UTC, wass3r commented
works for me

2022-03-09 13:18 UTC, wass3r approved these changes

2022-03-09 13:42 UTC, plyr4 approved these changes

2022-03-09 18:15 UTC, merged