Enhance/scheduled build branches
go-vela/ui pull request #714
Opened 2023-08-28 18:07 UTC by claire1618

Adding a branch field to scheduled builds, so this adds a column in the schedules builds table and an input box for the user to specify the branch wanted for a scheduled build

2023-08-30 11:49 UTC, JordanSussman commented
Is the branch going to be a required field that the user provides? If not, can you update the input box to clarify the behavior when no branch is provided?

2023-08-30 13:58 UTC, ecrupper requested changes
I think some Cypress tests need addressed too, but other than that there were a couple things I noticed

2023-08-30 13:58 UTC, ecrupper commented on src/elm/Pages/Schedules/Form.elm
> +                    [ em [] [ text "(Leave blank to default to main)" ]
```suggestion
                    [ em [] [ text "(Leave blank to use default branch)" ]
```

Won't always be main

2023-08-30 13:58 UTC, ecrupper commented on docker-compose.yml
> -      QUEUE_PRIVATE_KEY: 'tCIevHOBq6DdN5SSBtteXUusjjd0fOqzk2eyi0DMq04NewmShNKQeUbbp3vkvIckb4pCxc+vxUo+mYf/vzOaSg=='
We'll want to keep these compose values

2023-09-06 13:56 UTC, plyr4 commented on cypress/fixtures/schedule.json
> +  "branch": "master",
```suggestion
  "branch": "main",
```

2023-09-06 13:56 UTC, plyr4 commented on cypress/fixtures/schedule.json
> +  "branch": "master",
not a comment for you but we should really change all these master references to main

2023-09-06 13:58 UTC, plyr4 commented on src/elm/Pages/Schedules/Form.elm
> +        ]
```suggestion
viewBranchNameInput : String -> Bool -> Html Msg
viewBranchNameInput val disable =
    section [ class "form-control", class "-stack" ]
        [ label [ class "form-label", for <| "schedule-branch-name" ]
            [ strong [] [ text "Branch" ]
            , span
                [ class "field-description" ]
                [ em [] [ text "(Leave blank to use default branch)" ]
                ]
            ]
        , input
            [ disabled disable
            , value val
            , onInput <|
                OnChangeStringField "branch"
            , placeholder "Branch Name"
            , id "schedule-branch-name"
            , Util.testAttribute "schedule-branch-name"
            ]
            []
        ]
```

2023-09-06 13:58 UTC, plyr4 commented on src/elm/Pages/Schedules/Form.elm
> +        ]
very tiny nitpick for consistency

2023-09-06 15:56 UTC, claire1618 commented on src/elm/Pages/Schedules/Form.elm
> +        ]
Fixed!

2023-09-07 15:15 UTC, merged