feat: adding a delete event
go-vela/ui pull request #759
Opened 2024-01-29 19:36 UTC by claire1618

Similar to the pull_request and push events, it would be beneficial if Vela could recognize the delete event. So the users would have the option to have Vela set off builds when a branch or tag are deleted in their repo.

The code here adds the Delete event to the checkboxes in Secrets and RepoSettings.

Goes along with: [https://github.com/go-vela/server/pull/1038](https://github.com/go-vela/server/pull/1038)

2024-01-29 20:08 UTC, timhuynh94 approved these changes

2024-01-30 16:06 UTC, ecrupper approved these changes

2024-01-30 16:08 UTC, ecrupper requested changes

2024-01-30 16:08 UTC, ecrupper commented on src/elm/Vela.elm
> +    { push = { branch = True, tag = True, delete_branch = True, delete_tag = True }, pull = defaultPullActionsPayload Nothing, deploy = { created = True }, comment = defaultCommentActionsPayload Noth
I'd say delete events should not be part of the default set for secrets. Let's just keep it to push, tag, and deployment 👍

2024-01-31 16:09 UTC, ecrupper approved these changes

2024-01-31 16:39 UTC, wass3rw3rk approved these changes

2024-01-31 16:45 UTC, merged